/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import javax.swing.WindowConstants;

/**
 *
 * @author jeremy
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    String user = Login.user;
    
    public Administrador() {
        initComponents();
        
        this.setTitle("Administrador - Sesion de " + user);
        this.setSize(650, 450);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.getContentPane().setBackground(new Color(255,255,255));

        label_Titulo.setText("Bienvenido " + user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_registrarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_GestionarUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boton_Usuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_Titulo = new javax.swing.JLabel();
        boton_Trabajador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_registrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        boton_registrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        boton_registrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_registrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_registrarUsuarioMouseExited(evt);
            }
        });
        boton_registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(boton_registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Registrar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        boton_GestionarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        boton_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        boton_GestionarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_GestionarUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_GestionarUsuariosMouseExited(evt);
            }
        });
        boton_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 100));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Gestionar Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        boton_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        boton_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        boton_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_UsuarioMouseExited(evt);
            }
        });
        boton_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 120, 100));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Panel Vista Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        label_Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label_Titulo.setForeground(new java.awt.Color(255, 153, 0));
        label_Titulo.setText("Bienvenido");
        getContentPane().add(label_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        boton_Trabajador.setBackground(new java.awt.Color(255, 255, 255));
        boton_Trabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capturista.png"))); // NOI18N
        boton_Trabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_TrabajadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_TrabajadorMouseExited(evt);
            }
        });
        boton_Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_TrabajadorActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Panel Vista Trabajador  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarUsuarioActionPerformed

        new RegistrarUsuarios().setVisible(true);

    }//GEN-LAST:event_boton_registrarUsuarioActionPerformed

    private void boton_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarUsuariosActionPerformed

        new GestionarUsuarios().setVisible(true);

    }//GEN-LAST:event_boton_GestionarUsuariosActionPerformed

    private void boton_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_UsuarioActionPerformed

        new Usuarios().setVisible(true);
        
    }//GEN-LAST:event_boton_UsuarioActionPerformed

    private void boton_TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_TrabajadorActionPerformed
        new Trabajador().setVisible(true);
    }//GEN-LAST:event_boton_TrabajadorActionPerformed

    private void boton_registrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_registrarUsuarioMouseEntered
        boton_registrarUsuario.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_boton_registrarUsuarioMouseEntered

    private void boton_registrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_registrarUsuarioMouseExited
        boton_registrarUsuario.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_boton_registrarUsuarioMouseExited

    private void boton_GestionarUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_GestionarUsuariosMouseEntered
        boton_GestionarUsuarios.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_boton_GestionarUsuariosMouseEntered

    private void boton_GestionarUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_GestionarUsuariosMouseExited
        boton_GestionarUsuarios.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_boton_GestionarUsuariosMouseExited

    private void boton_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_UsuarioMouseEntered
        boton_Usuario.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_boton_UsuarioMouseEntered

    private void boton_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_UsuarioMouseExited
        boton_Usuario.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_boton_UsuarioMouseExited

    private void boton_TrabajadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_TrabajadorMouseEntered
        boton_Trabajador.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_boton_TrabajadorMouseEntered

    private void boton_TrabajadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_TrabajadorMouseExited
        boton_Trabajador.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_boton_TrabajadorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_GestionarUsuarios;
    private javax.swing.JButton boton_Trabajador;
    private javax.swing.JButton boton_Usuario;
    private javax.swing.JButton boton_registrarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_Titulo;
    // End of variables declaration//GEN-END:variables
}
