/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import javax.swing.WindowConstants;
import java.sql.*;
import clases.Conexion;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author jeremy
 */

public class InformacionRemolque extends javax.swing.JFrame {

    /**
     * Creates new form InformacionCamion
     */
    String user = Login.user;
    int idRemolque = GestionDeRemolques.id_remolqueUpdate;
       
    public InformacionRemolque() {
        initComponents();

        this.setTitle("Informacion de Remolque");
        this.setSize(615, 410);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(255, 255, 255));
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select conductor, productos, tipo_remolque , modelo, marca, estatus from camiones where ID = '" + idRemolque + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                txt_conductor.setText(rs.getString(1));
                txt_productos.setText(rs.getString(2));
                cmb_tipoRemolque.setSelectedItem(rs.getObject(3));
                txt_modelo.setText(rs.getString(4));
                cmb_marca.setSelectedItem(rs.getObject(5));
                cmb_estatus.setSelectedItem(rs.getObject(6));
                
            }
            
            
            
            cn.close();
            
        } catch (SQLException e) {
            System.err.println("Error al llenar la tabla de Informacion Remolque");
            JOptionPane.showMessageDialog(null, "Error al llenar la tabla, Contacte con el Administrador" );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_registrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_conductor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_marca = new javax.swing.JComboBox<>();
        boton_acoplarRemolque = new javax.swing.JButton();
        boton_modificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_productos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmb_tipoRemolque = new javax.swing.JComboBox<>();

        boton_registrar.setBackground(new java.awt.Color(255, 153, 0));
        boton_registrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_registrar.setForeground(new java.awt.Color(255, 255, 255));
        boton_registrar.setText("Registrar");
        boton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Informacion de Remolque");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Conductor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_conductor.setBackground(new java.awt.Color(255, 153, 0));
        txt_conductor.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_conductor.setForeground(new java.awt.Color(255, 255, 255));
        txt_conductor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_conductor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 29));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Asignado", "Volvo", "Scania", "Man", "Peterbilt", "Kenworth", "Iveco", "Mack", "Freightliner", "Renault", "Ford" }));
        cmb_marca.setEnabled(false);
        cmb_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_marcaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 28));

        boton_acoplarRemolque.setBackground(new java.awt.Color(255, 153, 0));
        boton_acoplarRemolque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_acoplarRemolque.setForeground(new java.awt.Color(255, 255, 255));
        boton_acoplarRemolque.setText("Acoplar Camion");
        boton_acoplarRemolque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_acoplarRemolqueActionPerformed(evt);
            }
        });
        getContentPane().add(boton_acoplarRemolque, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 230, 40));

        boton_modificar.setBackground(new java.awt.Color(255, 153, 0));
        boton_modificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boton_modificar.setForeground(new java.awt.Color(255, 255, 255));
        boton_modificar.setText("Modificar");
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 230, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Modelo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        txt_modelo.setEditable(false);
        txt_modelo.setBackground(new java.awt.Color(255, 153, 0));
        txt_modelo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 230, 29));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Estatus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Ocupado" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 28));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Productos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txt_productos.setBackground(new java.awt.Color(255, 153, 0));
        txt_productos.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txt_productos.setForeground(new java.awt.Color(255, 255, 255));
        txt_productos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 29));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Tipo Remolque:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        cmb_tipoRemolque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Remolque de enganche", "Remolque con eje central", "Semirremolque" }));
        getContentPane().add(cmb_tipoRemolque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrarActionPerformed

    }//GEN-LAST:event_boton_registrarActionPerformed

    private void boton_acoplarRemolqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_acoplarRemolqueActionPerformed

        new AcoplarCamion().setVisible(true);

    }//GEN-LAST:event_boton_acoplarRemolqueActionPerformed

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        
        String conductor = txt_conductor.getText();
        String productos = txt_productos.getText();
        String tipo_remolque = cmb_tipoRemolque.getSelectedItem().toString();
        String estatus = cmb_estatus.getSelectedItem().toString();
        
        try {
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "update camiones set conductor = ?, productos = ?, tipo_remolque = ?, estatus = ? where ID = '" + idRemolque + "'");
            
            pst.setString(1, conductor);
            pst.setString(2, productos);
            pst.setString(3, tipo_remolque);
            pst.setString(4, estatus);
            
            pst.executeUpdate();

            cn.close();
            txt_conductor.setBackground(Color.green);
            txt_productos.setBackground(Color.green);
            cmb_tipoRemolque.setBackground(Color.green);
            cmb_estatus.setBackground(Color.green);
            
            JOptionPane.showMessageDialog(null, "Remolque Modificado con Exito");
            this.dispose();
            
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al modificar Remolque, Contacte con el Administrador");
            System.err.println("Error al modificar Remolque : \n" + e);
        }
    }//GEN-LAST:event_boton_modificarActionPerformed

    private void cmb_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_marcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionRemolque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionRemolque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionRemolque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionRemolque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionRemolque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_acoplarRemolque;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JButton boton_registrar;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JComboBox<String> cmb_tipoRemolque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_conductor;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_productos;
    // End of variables declaration//GEN-END:variables
}
