/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import clases.Conexion;
import java.awt.HeadlessException;
import java.sql.*;

/**
 *
 * @author jeremy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static String user = "";
    public static int bandera = 0;
    
    public Login() {
        initComponents();
        
        this.setTitle("GTruck - Bienvenido Al Sistema");
        this.setResizable(false);
        this.setSize(415, 550);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.getContentPane().setBackground(new Color(255, 255, 255));
        
        ImageIcon imagenUser = new ImageIcon("src/images/usuario.jpg");
        Icon iconoUsuario = new ImageIcon(imagenUser.getImage().getScaledInstance(label_imagenUser.getWidth(), label_imagenUser.getHeight(), Image.SCALE_DEFAULT));
        label_imagenUser.setIcon(iconoUsuario);
        repaint();
        
        ImageIcon imagenCandado = new ImageIcon("src/images/candado.jpg");
        Icon iconoCandado = new ImageIcon(imagenCandado.getImage().getScaledInstance(label_imagenPass.getWidth(), label_imagenPass.getHeight(), Image.SCALE_DEFAULT));
        label_imagenPass.setIcon(iconoCandado);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_imagenUser = new javax.swing.JLabel();
        label_imagenPass = new javax.swing.JLabel();
        label_Login = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        boton_iniciarSesion = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        label_passOlvidada = new javax.swing.JLabel();
        label_registrarse = new javax.swing.JLabel();
        label_textoRegistrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_imagenUser.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_imagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 30, 30));

        label_imagenPass.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label_imagenPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 30, 30));

        label_Login.setBackground(new java.awt.Color(255, 255, 255));
        label_Login.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_Login.setText("Login");
        getContentPane().add(label_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 48, -1, -1));

        txt_user.setBackground(new java.awt.Color(204, 204, 204));
        txt_user.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 110, 330, 35));

        boton_iniciarSesion.setBackground(new java.awt.Color(255, 153, 0));
        boton_iniciarSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        boton_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        boton_iniciarSesion.setText("Iniciar Sesion");
        boton_iniciarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_iniciarSesion.setBorderPainted(false);
        boton_iniciarSesion.setFocusPainted(false);
        boton_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_iniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(boton_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 239, 330, 44));

        txt_pass.setBackground(new java.awt.Color(204, 204, 204));
        txt_pass.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 163, 330, 35));

        label_passOlvidada.setBackground(new java.awt.Color(255, 255, 255));
        label_passOlvidada.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_passOlvidada.setForeground(new java.awt.Color(204, 204, 204));
        label_passOlvidada.setText("Contraseña Olvidada");
        label_passOlvidada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_passOlvidadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_passOlvidadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_passOlvidadaMouseExited(evt);
            }
        });
        getContentPane().add(label_passOlvidada, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 301, -1, -1));

        label_registrarse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_registrarse.setForeground(new java.awt.Color(81, 209, 246));
        label_registrarse.setText("Registrarse");
        label_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_registrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_registrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_registrarseMouseExited(evt);
            }
        });
        getContentPane().add(label_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 481, -1, -1));

        label_textoRegistrarse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_textoRegistrarse.setForeground(new java.awt.Color(204, 204, 204));
        label_textoRegistrarse.setText("¿Nuevo en el Sistema?: ");
        getContentPane().add(label_textoRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 481, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_passOlvidadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_passOlvidadaMouseEntered
        label_passOlvidada.setForeground(new Color(255, 153, 0));
        label_passOlvidada.setText("C̲o̲n̲t̲r̲a̲s̲e̲ñ̲a̲ O̲l̲v̲i̲d̲a̲d̲a̲");
    }//GEN-LAST:event_label_passOlvidadaMouseEntered

    private void label_passOlvidadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_passOlvidadaMouseExited
        label_passOlvidada.setForeground(new Color(204, 204, 204));
        label_passOlvidada.setText("Contraseña Olvidada");
    }//GEN-LAST:event_label_passOlvidadaMouseExited

    private void label_registrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registrarseMouseEntered
        label_registrarse.setText("R̲e̲g̲i̲s̲t̲r̲a̲r̲s̲e̲");
    }//GEN-LAST:event_label_registrarseMouseEntered

    private void label_registrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registrarseMouseExited
        label_registrarse.setText("Registrarse");
    }//GEN-LAST:event_label_registrarseMouseExited

    private void boton_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_iniciarSesionActionPerformed
        
        user = txt_user.getText();
        String pass = txt_pass.getText().trim();
        
        if (!user.equals("") && !pass.equals("")) {
            
            try {
                
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("select tipo_nivel from usuarios where user = '" + user + "' and pass = '" + pass + "'");
                
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    
                    String tipo_nivel = rs.getString(1);
                    
                    if (tipo_nivel.equalsIgnoreCase("Administrador")) {
                        cn.close();
                        bandera = 1;
                        dispose();
                        new Administrador().setVisible(true);
                        
                    } else if (tipo_nivel.equalsIgnoreCase("Trabajador")) {
                        cn.close();
                        dispose();                        
                        new Trabajador().setVisible(true);
                        
                    } else if (tipo_nivel.equalsIgnoreCase("Usuario")) {
                        cn.close();
                        dispose();
                        new Usuarios().setVisible(true);
                        
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Datos de Acceso Incorrectos");
                    txt_user.setText("");
                    txt_pass.setText("");
                }
                
            } catch (HeadlessException | SQLException e) {
                System.err.println("Error, al Iniciar Sesion : \n" + e);
                JOptionPane.showMessageDialog(null, "Error, al Iniciar Sesion, Contacte con el Administrador");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes de Llenar todos los datos");
        }
    }//GEN-LAST:event_boton_iniciarSesionActionPerformed

    private void label_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registrarseMouseClicked
        new Registrarse().setVisible(true);
    }//GEN-LAST:event_label_registrarseMouseClicked

    private void label_passOlvidadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_passOlvidadaMouseClicked
        JOptionPane.showMessageDialog(null, "\n Esta Aplicacion es Gratuita y Local, \n Ingresa a http://localhost/phpmyadmin/ - Base de datos - \n bd_gt - usuarios. \n Puedes Editar Y/O Modificar los usuarios \n");
    }//GEN-LAST:event_label_passOlvidadaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_iniciarSesion;
    private javax.swing.JLabel label_Login;
    private javax.swing.JLabel label_imagenPass;
    private javax.swing.JLabel label_imagenUser;
    private javax.swing.JLabel label_passOlvidada;
    private javax.swing.JLabel label_registrarse;
    private javax.swing.JLabel label_textoRegistrarse;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
