/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import javax.swing.WindowConstants;

/**
 *
 * @author jeremy
 */
public class Trabajador extends javax.swing.JFrame {

    /**
     * Creates new form Trabajador
     */
    String user = Login.user;
    int bandera = Login.bandera;
    
    public Trabajador() {
        initComponents();
        
        this.setTitle("Trabajador - Sesion de " + user);
        this.setSize(650, 450);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(255, 255, 255));
        
        if (bandera == 1) {
            this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        
        label_Titulo.setText("Bienvenido " + user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        boton_RegistrarRemolque = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        boton_RegistrarViaje = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        label_Titulo = new javax.swing.JLabel();
        boton_RegistrarCamion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        boton_gestionarCamion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        boton_gestionarRemolque = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        boton_GestionarViaje = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_RegistrarRemolque.setBackground(new java.awt.Color(255, 255, 255));
        boton_RegistrarRemolque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remolque.png"))); // NOI18N
        boton_RegistrarRemolque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_RegistrarRemolque.setFocusPainted(false);
        boton_RegistrarRemolque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_RegistrarRemolqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_RegistrarRemolqueMouseExited(evt);
            }
        });
        boton_RegistrarRemolque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RegistrarRemolqueActionPerformed(evt);
            }
        });
        getContentPane().add(boton_RegistrarRemolque, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 130, 120));

        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Registrar Remolque");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 20));

        boton_RegistrarViaje.setBackground(new java.awt.Color(255, 255, 255));
        boton_RegistrarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viaje.jpg"))); // NOI18N
        boton_RegistrarViaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_RegistrarViaje.setFocusPainted(false);
        boton_RegistrarViaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_RegistrarViajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_RegistrarViajeMouseExited(evt);
            }
        });
        boton_RegistrarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RegistrarViajeActionPerformed(evt);
            }
        });
        getContentPane().add(boton_RegistrarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 70, 140, 120));

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Registrar Viaje");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        label_Titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label_Titulo.setForeground(new java.awt.Color(255, 153, 0));
        label_Titulo.setText("Bienvenido");
        getContentPane().add(label_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        boton_RegistrarCamion.setBackground(new java.awt.Color(255, 255, 255));
        boton_RegistrarCamion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camion.png"))); // NOI18N
        boton_RegistrarCamion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_RegistrarCamion.setFocusPainted(false);
        boton_RegistrarCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_RegistrarCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_RegistrarCamionMouseExited(evt);
            }
        });
        boton_RegistrarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_RegistrarCamionActionPerformed(evt);
            }
        });
        getContentPane().add(boton_RegistrarCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 120));

        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Registrar Camion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        boton_gestionarCamion.setBackground(new java.awt.Color(255, 255, 255));
        boton_gestionarCamion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_gestionar/camion_gestionar.png"))); // NOI18N
        boton_gestionarCamion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_gestionarCamion.setFocusPainted(false);
        boton_gestionarCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_gestionarCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_gestionarCamionMouseExited(evt);
            }
        });
        boton_gestionarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_gestionarCamionActionPerformed(evt);
            }
        });
        getContentPane().add(boton_gestionarCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 120));

        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Gestion de Camiones");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        boton_gestionarRemolque.setBackground(new java.awt.Color(255, 255, 255));
        boton_gestionarRemolque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_gestionar/remolque_gestionar.png"))); // NOI18N
        boton_gestionarRemolque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_gestionarRemolque.setFocusPainted(false);
        boton_gestionarRemolque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_gestionarRemolqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_gestionarRemolqueMouseExited(evt);
            }
        });
        boton_gestionarRemolque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_gestionarRemolqueActionPerformed(evt);
            }
        });
        getContentPane().add(boton_gestionarRemolque, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 120));

        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Gestion de Remolques");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, 20));

        boton_GestionarViaje.setBackground(new java.awt.Color(255, 255, 255));
        boton_GestionarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_gestionar/viaje_gestionar.jpg"))); // NOI18N
        boton_GestionarViaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_GestionarViaje.setFocusPainted(false);
        boton_GestionarViaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_GestionarViajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_GestionarViajeMouseExited(evt);
            }
        });
        boton_GestionarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_GestionarViajeActionPerformed(evt);
            }
        });
        getContentPane().add(boton_GestionarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 140, 120));

        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Gestion de Viajes");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_RegistrarRemolqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RegistrarRemolqueActionPerformed
        
        new RegistrarRemolque().setVisible(true);
    }//GEN-LAST:event_boton_RegistrarRemolqueActionPerformed

    private void boton_RegistrarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RegistrarViajeActionPerformed
        
        new RegistrarViaje().setVisible(true);
    }//GEN-LAST:event_boton_RegistrarViajeActionPerformed

    private void boton_RegistrarViajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_RegistrarViajeMouseEntered
        boton_RegistrarViaje.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_boton_RegistrarViajeMouseEntered

    private void boton_RegistrarViajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_RegistrarViajeMouseExited
        boton_RegistrarViaje.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_boton_RegistrarViajeMouseExited

    private void boton_RegistrarRemolqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_RegistrarRemolqueMouseEntered
        boton_RegistrarRemolque.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_boton_RegistrarRemolqueMouseEntered

    private void boton_RegistrarRemolqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_RegistrarRemolqueMouseExited
        boton_RegistrarRemolque.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_boton_RegistrarRemolqueMouseExited

    private void boton_RegistrarCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_RegistrarCamionMouseEntered
        boton_RegistrarCamion.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_boton_RegistrarCamionMouseEntered

    private void boton_RegistrarCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_RegistrarCamionMouseExited
        boton_RegistrarCamion.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_boton_RegistrarCamionMouseExited

    private void boton_RegistrarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RegistrarCamionActionPerformed
        new RegistrarCamion().setVisible(true);
    }//GEN-LAST:event_boton_RegistrarCamionActionPerformed

    private void boton_gestionarCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_gestionarCamionMouseEntered
        boton_gestionarCamion.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_boton_gestionarCamionMouseEntered

    private void boton_gestionarCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_gestionarCamionMouseExited
        boton_gestionarCamion.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_boton_gestionarCamionMouseExited

    private void boton_gestionarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_gestionarCamionActionPerformed
        new GestionDeCamiones().setVisible(true);
    }//GEN-LAST:event_boton_gestionarCamionActionPerformed

    private void boton_gestionarRemolqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_gestionarRemolqueMouseEntered
        boton_gestionarRemolque.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_boton_gestionarRemolqueMouseEntered

    private void boton_gestionarRemolqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_gestionarRemolqueMouseExited
        boton_gestionarRemolque.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_boton_gestionarRemolqueMouseExited

    private void boton_gestionarRemolqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_gestionarRemolqueActionPerformed
        new GestionDeRemolques().setVisible(true);
    }//GEN-LAST:event_boton_gestionarRemolqueActionPerformed

    private void boton_GestionarViajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_GestionarViajeMouseEntered
        boton_GestionarViaje.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_boton_GestionarViajeMouseEntered

    private void boton_GestionarViajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_GestionarViajeMouseExited
        boton_GestionarViaje.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_boton_GestionarViajeMouseExited

    private void boton_GestionarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_GestionarViajeActionPerformed
        new GestionDeViajes().setVisible(true);
    }//GEN-LAST:event_boton_GestionarViajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_GestionarViaje;
    private javax.swing.JButton boton_RegistrarCamion;
    private javax.swing.JButton boton_RegistrarRemolque;
    private javax.swing.JButton boton_RegistrarViaje;
    private javax.swing.JButton boton_gestionarCamion;
    private javax.swing.JButton boton_gestionarRemolque;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_Titulo;
    // End of variables declaration//GEN-END:variables
}
